version: "3"
services:
  liuli_api:
    image: liuliio/api:v0.1.0
    restart: always
    container_name: liuli_api
    ports:
      - "8060:8060"
    volumes:
      - ./pro.env:/data/code/pro.env
    links:
      - liuli_mongodb
    depends_on:
      - liuli_mongodb
    networks:
      - liuli-network
  liuli_schedule:
    image: liuliio/schedule:v0.1.2
    restart: always
    container_name: liuli_schedule
    volumes:
      - ./pro.env:/data/code/pro.env
    links:
      - liuli_mongodb
    depends_on:
      - liuli_mongodb
    networks:
      - liuli-network
  liuli_mongodb:
    image: mongo:3.6
    restart: always
    container_name: liuli_mongodb
    ports:
      - "27027:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - liuli-network

networks:
  liuli-network:
    driver: bridge
